require 'forwardable'
require 'colorize'
require 'pry'
require 'pry-rescue'
require 'optparse'
require 'yaml'
require 'pathname'
require 'open-uri'
require 'securerandom'
require 'tsort'
require 'ostruct'
require 'date'
require 'nokogiri'
require 'nokogumbo'
require 'pdf-reader'
require 'json'
require 'zip'
require 'aixm'

require 'active_support'
require 'active_support/core_ext/object/blank'
require 'active_support/core_ext/string'
require_relative 'core_ext/object'
require_relative 'core_ext/string'
require_relative 'core_ext/nil_class'
require_relative 'core_ext/enumerable'

require_relative 'aipp/version'
require_relative 'aipp/pdf'
require_relative 'aipp/t_hash'
require_relative 'aipp/executable'
require_relative 'aipp/airac'
require_relative 'aipp/aip'
require_relative 'aipp/parser'
require_relative 'aipp/downloader'
require_relative 'aipp/callback'

# Disable "did you mean?" suggestions
module DidYouMean::Correctable
  remove_method :to_s
end
