#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  ruby '>= 2.5'
  gem 'aipp', '~> 0'
end

executable = AIPP::Executable.new(schema: File.basename($0)[4..-1].to_sym)
executable.run
