#!/usr/bin/env ruby

# TODO: hide deprecations unless in gem root until fully complying with Ruby 2.7
Warning[:deprecated] = false # Dir.pwd.match? /aipp$/

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  ruby '>= 2.7'
  gem 'aipp', '~> 0'
end

AIPP::Executable.new(schema: File.basename($0)[4..-1].to_sym).run
